apiVersion: singlestore.terasky.com/v1alpha1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: singlestore/v1alpha1/workspace
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    kaiEnabled: true
    name: workspace
    size: S-00
    suspended: false
    workspaceGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: singlestore.terasky.com/v1alpha1
kind: WorkspaceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: singlestore/v1alpha1/workspace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    expiresAt: "2222-01-01T00:00:00Z"
    firewallRanges:
    - 0.0.0.0/0
    name: group
    regionId: ${data.singlestoredb_regions.all.regions.0.id}
