name: singlestore-labs/singlestoredb
resources:
    singlestoredb_workspace:
        subCategory: ""
        description: This resource enables the management of SingleStoreDB workspaces.
        name: singlestoredb_workspace
        title: singlestoredb_workspace Resource - terraform-provider-singlestoredb
        examples:
            - name: this
              manifest: |-
                {
                  "kai_enabled": true,
                  "name": "workspace",
                  "size": "S-00",
                  "suspended": false,
                  "workspace_group_id": "${singlestoredb_workspace_group.example.id}"
                }
              references:
                workspace_group_id: singlestoredb_workspace_group.example.id
              dependencies:
                singlestoredb_workspace_group.example: |-
                    {
                      "expires_at": "2222-01-01T00:00:00Z",
                      "firewall_ranges": [
                        "0.0.0.0/0"
                      ],
                      "name": "group",
                      "region_id": "${data.singlestoredb_regions.all.regions.0.id}"
                    }
        argumentDocs:
            created_at: (String) The timestamp when the workspace was created.
            endpoint: (String) The endpoint used to connect to the workspace.
            id: (String) The unique identifier of the workspace.
            kai_enabled: (Boolean) Whether the Kai API is enabled for the workspace.
            name: (String) The name assigned to the workspace.
            size: (String) The size of the workspace, specified in workspace size notation (S-00, S-0, S-1, S-2).
            suspended: (Boolean) The status of the workspace. If true, the workspace is suspended.
            workspace_group_id: (String) The unique identifier of the workspace group that the workspace belongs to.
        importStatements: []
    singlestoredb_workspace_group:
        subCategory: ""
        description: Manage SingleStoreDB workspace groups with this resource.
        name: singlestoredb_workspace_group
        title: singlestoredb_workspace_group Resource - terraform-provider-singlestoredb
        examples:
            - name: this
              manifest: |-
                {
                  "admin_password": "fooBAR12$",
                  "expires_at": "2222-01-01T00:00:00Z",
                  "firewall_ranges": [
                    "0.0.0.0/0"
                  ],
                  "name": "group",
                  "region_id": "${data.singlestoredb_regions.all.regions.0.id}"
                }
              references:
                region_id: data.singlestoredb_regions.all.regions.0.id
        argumentDocs:
            admin_password: (String, Sensitive) The admin SQL user password for the workspace group. If not provided, the server will automatically generate a secure password. Please note that updates to the admin password might take a brief moment to become effective.
            created_at: (String) The timestamp when the workspace was created.
            expires_at: (String) The expiration timestamp of the workspace group. If not specified, the workspace group never expires. Upon expiration, the workspace group is terminated and all its data is lost. Set the expiration time as an RFC3339 UTC timestamp, e.g., "2221-01-02T15:04:05Z".
            firewall_ranges: (List of String) List of allowed CIDR ranges. An empty list blocks all inbound requests. For unrestricted traffic, use ["0.0.0.0/0"]. Note that updates to firewall ranges may take a brief moment to become effective.
            id: (String) The unique identifier of the workspace group.
            name: (String) Name of the workspace group.
            region_id: (String) The unique identifier of the region where the workspace group is to be created.
        importStatements: []
