// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Workspace.
func (mg *Workspace) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.WorkspaceGroupID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.WorkspaceGroupIDRef,
		Selector:     mg.Spec.ForProvider.WorkspaceGroupIDSelector,
		To: reference.To{
			List:    &WorkspaceGroupList{},
			Managed: &WorkspaceGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.WorkspaceGroupID")
	}
	mg.Spec.ForProvider.WorkspaceGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.WorkspaceGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.WorkspaceGroupID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.WorkspaceGroupIDRef,
		Selector:     mg.Spec.InitProvider.WorkspaceGroupIDSelector,
		To: reference.To{
			List:    &WorkspaceGroupList{},
			Managed: &WorkspaceGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.WorkspaceGroupID")
	}
	mg.Spec.InitProvider.WorkspaceGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.WorkspaceGroupIDRef = rsp.ResolvedReference

	return nil
}
